# Generated by Django 4.2.6 on 2023-10-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_image'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='food',
            new_name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='foods',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foods.food'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
